export const navigation = [
  {
    title: 'Introduction',
    links: [
      { title: 'Getting started', href: '/' },
      { title: 'Installation', href: '/docs/installation' },
    ],
  },
  {
    title: 'Framework',
    links: [
      { title: 'Lifecycle & DI', href: '/docs/lifecycle' },
      { title: 'Configuration', href: '/docs/configuration' },
      { title: 'HTTP routing', href: '/docs/http' },
      { title: 'SQLite database', href: '/docs/sqlite' },
      { title: 'Authentication', href: '/docs/auth' },
      { title: 'Validation', href: '/docs/validation' },
      { title: 'Email', href: '/docs/email' },
      { title: 'Cache', href: '/docs/cache' },
      { title: 'Webhooks', href: '/docs/webhook' },
      { title: 'Logging', href: '/docs/logging' },
    ],
  },
  {
    title: 'Background processing',
    links: [
      { title: 'Cron scheduler', href: '/docs/cron' },
      { title: 'Job queue', href: '/docs/queue' },
    ],
  },
  {
    title: 'Recipes',
    links: [
      { title: 'Adding a module', href: '/docs/recipes/modules' },
      { title: 'Adding an admin page', href: '/docs/recipes/admin-pages' },
      { title: 'Database migrations', href: '/docs/recipes/migrations' },
      { title: 'Database schema design', href: '/docs/recipes/schema-design' },
      { title: 'Database transactions', href: '/docs/recipes/transactions' },
      { title: 'Input validation', href: '/docs/recipes/validation' },
      { title: 'Password reset', href: '/docs/recipes/password-reset' },
      { title: 'Session management', href: '/docs/recipes/session-management' },
      { title: 'Notifications', href: '/docs/recipes/notifications' },
      { title: 'File uploads', href: '/docs/recipes/file-uploads' },
      { title: 'Custom cron jobs', href: '/docs/recipes/cron-jobs' },
      { title: 'Queue jobs', href: '/docs/recipes/queue-jobs' },
      { title: 'Roles & scopes', href: '/docs/recipes/roles-scopes' },
      { title: 'Real-time with WebSocket', href: '/docs/recipes/real-time' },
      { title: 'Caching', href: '/docs/recipes/caching' },
      { title: 'Webhooks', href: '/docs/recipes/webhooks' },
      { title: 'User API keys', href: '/docs/recipes/user-api-keys' },
      { title: 'User settings', href: '/docs/recipes/user-settings' },
      { title: 'User activity log', href: '/docs/recipes/user-activity' },
      { title: 'Paginated lists', href: '/docs/recipes/paginated-lists' },
      { title: 'Automated backups', href: '/docs/recipes/automated-backups' },
      { title: 'Audit logging', href: '/docs/recipes/audit-logging' },
      { title: 'Custom middleware', href: '/docs/recipes/custom-middleware' },
      { title: 'Error handling', href: '/docs/recipes/error-handling' },
      { title: 'Performance tuning', href: '/docs/recipes/performance-tuning' },
      { title: 'Testing', href: '/docs/recipes/testing' },
      { title: 'Deployment', href: '/docs/recipes/deployment' },
    ],
  },
  {
    title: 'Tooling',
    links: [
      { title: 'CLI commands', href: '/docs/cli' },
    ],
  },
]
