export const navigation = [
  {
    title: 'Introduction',
    links: [
      { title: 'Getting started', href: '/' },
      { title: 'Installation', href: '/installation' },
      { title: 'Customizing your fork', href: '/customizing' },
      { title: 'API reference', href: '/api-reference' },
    ],
  },
  {
    title: 'Framework',
    links: [
      { title: 'Lifecycle & DI', href: '/lifecycle' },
      { title: 'Configuration', href: '/configuration' },
      { title: 'HTTP routing', href: '/http' },
      { title: 'SQLite database', href: '/sqlite' },
      { title: 'Authentication', href: '/auth' },
      { title: 'Validation', href: '/validation' },
      { title: 'Email', href: '/email' },
      { title: 'Cache', href: '/cache' },
      { title: 'Webhooks', href: '/webhook' },
      { title: 'Metrics', href: '/metrics' },
      { title: 'Logging', href: '/logging' },
      { title: 'CLI toolkit', href: '/cmd' },
    ],
  },
  {
    title: 'Background processing',
    links: [
      { title: 'Task pool', href: '/task' },
      { title: 'Cron scheduler', href: '/cron' },
      { title: 'Job queue', href: '/queue' },
    ],
  },
  {
    title: 'Recipes',
    links: [
      { title: 'Adding a module', href: '/recipes/modules' },
      { title: 'Adding an admin page', href: '/recipes/admin-pages' },
      { title: 'Admin dashboard patterns', href: '/recipes/dashboard-patterns' },
      { title: 'Configuration management', href: '/recipes/configuration' },
      { title: 'Database migrations', href: '/recipes/migrations' },
      { title: 'Database schema design', href: '/recipes/schema-design' },
      { title: 'Database transactions', href: '/recipes/transactions' },
      { title: 'Data encryption', href: '/recipes/data-encryption' },
      { title: 'Input validation', href: '/recipes/validation' },
      { title: 'Password reset', href: '/recipes/password-reset' },
      { title: 'Sending emails', href: '/recipes/sending-emails' },
      { title: 'Session management', href: '/recipes/session-management' },
      { title: 'Notifications', href: '/recipes/notifications' },
      { title: 'File uploads', href: '/recipes/file-uploads' },
      { title: 'Custom cron jobs', href: '/recipes/cron-jobs' },
      { title: 'Queue jobs', href: '/recipes/queue-jobs' },
      { title: 'Roles & scopes', href: '/recipes/roles-scopes' },
      { title: 'Real-time with WebSocket', href: '/recipes/real-time' },
      { title: 'Server-Sent Events', href: '/recipes/server-sent-events' },
      { title: 'Caching', href: '/recipes/caching' },
      { title: 'Webhooks', href: '/recipes/webhooks' },
      { title: 'User API keys', href: '/recipes/user-api-keys' },
      { title: 'User settings', href: '/recipes/user-settings' },
      { title: 'User activity log', href: '/recipes/user-activity' },
      { title: 'Paginated lists', href: '/recipes/paginated-lists' },
      { title: 'Search & filtering', href: '/recipes/search-filtering' },
      { title: 'Bulk operations', href: '/recipes/bulk-operations' },
      { title: 'Automated backups', href: '/recipes/automated-backups' },
      { title: 'Audit logging', href: '/recipes/audit-logging' },
      { title: 'Custom middleware', href: '/recipes/custom-middleware' },
      { title: 'Rate limiting', href: '/recipes/rate-limiting' },
      { title: 'API versioning', href: '/recipes/api-versioning' },
      { title: 'Error handling', href: '/recipes/error-handling' },
      { title: 'Performance tuning', href: '/recipes/performance-tuning' },
      { title: 'Observability & health checks', href: '/recipes/observability' },
      { title: 'Testing', href: '/recipes/testing' },
      { title: 'Application metrics', href: '/recipes/application-metrics' },
      { title: 'Client-side analytics', href: '/recipes/client-analytics' },
      { title: 'Deployment', href: '/recipes/deployment' },
    ],
  },
  {
    title: 'Tooling',
    links: [
      { title: 'CLI commands', href: '/cli' },
    ],
  },
]
